# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: Nathan Allaire <nathan.allaire@polymtl.ca>
CodeOfConductContact: nathan.allaire@polymtl.ca
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.11'
License: MIT
LicenseCopyrightHolders: Nathan Allaire
MarkdownIndentation: 2
PackageName: IRBP
PackageOwner: nathanemac
PackageUUID: 04b49ee4-b9c7-538e-b9b0-cc085f9e0210
_commit: v0.14.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
